---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  storageClassName: registry-volume
  hostPath:
    path: /data/registry
