---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  storageClassName: demo-volume
  hostPath:
    path: /data/demo
