---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-backup-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: awx-backup-volume
  hostPath:
    path: /data/backup
