---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-backup-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: awx-backup-volume
