---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galaxy

resources:
  - namespace.yaml

  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/crds/pulpproject_v1beta1_pulp_crd.yaml
  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/crds/pulpproject_v1beta1_pulpbackup_crd.yaml
  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/crds/pulpproject_v1beta1_pulprestore_crd.yaml
  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/service_account.yaml
  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/cluster_role.yaml
  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/role.yaml
  - https://raw.githubusercontent.com/pulp/pulp-operator/0.3.0/deploy/role_binding.yaml
  - clusterrolebinding.yaml

  - operator.yaml
