kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pulp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pulp-operator
subjects:
  - kind: ServiceAccount
    name: pulp-operator
    namespace: default
