---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galaxy-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: galaxy-volume
