---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  # These parameters are designed for use with:
  # - AWX Operator: 0.15.0
  #   https://github.com/ansible/awx-operator/blob/0.15.0/README.md
  # - AWX: 19.5.0
  #   https://github.com/ansible/awx/blob/19.5.0/INSTALL.md

  admin_user: admin
  admin_password_secret: awx-admin-password

  ingress_type: ingress
  ingress_tls_secret: awx-secret-tls
  hostname: awx.example.com

  postgres_configuration_secret: awx-postgres-configuration

  postgres_storage_class: awx-postgres-volume
  postgres_storage_requirements:
    requests:
      storage: 2Gi

  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  # To run AWX on a node that does not meet resource requirements,
  # uncomment the following three lines
  #web_resource_requirements: {}
  #task_resource_requirements: {}
  #ee_resource_requirements: {}
