---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galaxy

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: galaxy-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

  - name: galaxy-admin-password
    type: Opaque
    literals:
      - password=Galaxy123!

resources:
  - namespace.yaml
  - pv.yaml
  - galaxy.yaml
