---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: galaxy-postgres-volume
  hostPath:
    path: /data/galaxy/postgres

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-pulp-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  storageClassName: galaxy-pulp-volume
  hostPath:
    path: /data/galaxy/pulp
